AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    myServiceApiGateway:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod
    myLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: index.handler
        Runtime: "nodejs12.x"
        Timeout: 10
        CodeUri: /path-to-s3-bucket/
        Events:
          ApiEvent:
            Type: Api
            Properties:
              Path: /
              Method: get
              RestApiId: 
                Ref: myServiceApiGateway
